version: "3"
services:
  computation:
    container_name: jupyter_container
    image: jupyter/scipy-notebook
    volumes:
      - ./:/home/jovyan/work
    ports:
      - "7777:8888"
    env_file: .env
  database:
    container_name: potgres_container
    image: postgres
    ports:
      - "5432:5432"
