version: "3"
services:
  computation:
    container_name: jupyter_container
    build: docker/jupyter
    volumes:
      - ./MarchMadness/:/home/jovyan/work
    ports:
      - "7777:8888"
    env_file:
      - config/jupyter.env
  database:
    container_name: postgres_container
    image: postgres
    ports:
      - "5432:5432"
  dashboard:
    container_name: superset_container
    image: tylerfowler/superset
    ports:
      - "7077:8088"
